version: '3'
services:
    pgdb:
      image: postgres:13
      container_name: pgdb
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
        - ./pgdb/dump.sql:/docker-entrypoint-initdb.d/movies_schema_dump.sql
      env_file:
        - ./config/.env
      expose:
        - "5432"
      restart: always


    django_proj:
      build: .
      container_name: django_proj
      volumes:
        - static_volume:/movies_admin/static
        - media_volume:/movies_admin/media
      expose:
        - "8000"
      links:
        - "pgdb:database"
      depends_on:
        - pgdb
      env_file:
        - ./config/.env
      restart: always



    nginx:
      image: nginx-django
      volumes:
        - ./src/configs/site.conf:/etc/nginx/conf.d/site.conf:ro
        - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
        -  static_volume:/var/www/static/
        -  media_volume:/var/www/media/
      ports:
        - "8123:80"
      depends_on:
        - django_proj




volumes:
  pgdbdata:
  static_volume:
  media_volume:
