version: '3'
services:
    pgdb:
      image: postgres:13
      container_name: pgdb
      volumes:
        - pgdbdata:/var/lib/postgresql/data/
        - ./pgdb/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
      env_file:
        - ./config/.env
      expose:
        - "5432"
      restart: always

    django_proj:
      build: .
      container_name: django_proj
      volumes:
        - static_volume:/movies_admin/static
#        - .:/usr/src/movies_admin
#      ports:
#        - 8000:8000
      expose:
        - "8000"
      links:
        - "pgdb:database"
      depends_on:
        - pgdb
      env_file:
        - ./config/.env
      restart: always


    nginx:
      image: nginx-django
      volumes:
        - ./src/configs/site.conf:/etc/nginx/conf.d/site.conf:ro
        - ./data:/data/:ro
        - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "8123:80"
      depends_on:
        - django_proj




volumes:
  pgdbdata:
  static_volume: